apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260623-004613-l8vre1jqmhhh-service
spec:
  selector:
    app: enterprise-system-20260623-004613-l8vre1jqmhhh
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
